apiVersion: v1
kind: Service
metadata:
  name: monero
spec:
  type: NodePort
  selector:
    app: monero
  ports:
  - port: 18080
    protocol: TCP
    targetPort: 18080
    nodePort: 18080
  - port: 18081
    protocol: TCP
    targetPort: 18081
    nodePort: 18081
